namespace: message-mcp

cache:
  name: redis-cache
  image:
    repository: redis
    tag: 8.6.1
  port: 6379

database:
  name: postgres-db
  user: postgres
  password: postgres
  port: 5432
  initScript: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );